"use client";
import { useMemo, useState } from "react";

type Form={title:string;client:string;site:string;address:string;start:string;review:string;activity:string;workers:string;supervisor:string;hours:string;competence:string;tools:string;materials:string;ppe:string;permits:string;isolations:string;emergency:string;rescue:string;welfare:string;sequence:string};
type Risk={activity:string;people:string;harm:string;existing:string;controls:string;hierarchy:string;owner:string;target:string;status:string;legal:string;reviewer:string;initialL:number;initialS:number;residualL:number;residualS:number};
const newRisk=():Risk=>({activity:"Describe where and when exposure occurs.",people:"Operatives, other contractors, visitors and members of the public",harm:"Serious injury or ill health arising from exposure to the hazard.",existing:"Site induction, supervision, segregated work area and pre-start briefing.",controls:"Eliminate the hazard where practicable. Confirm engineered protection, safe access, inspected equipment, exclusion controls and task-specific briefing.",hierarchy:"Engineering control",owner:"Site supervisor",target:"Before work starts",status:"Open",legal:"Health and Safety at Work etc. Act 1974; Management of Health and Safety at Work Regulations 1999",reviewer:"",initialL:3,initialS:4,residualL:1,residualS:4});
const initial:Form={title:"Roof plant replacement",client:"",site:"Northgate House",address:"24 Deansgate, Manchester, M3 1AZ",start:"",review:"",activity:"Remove the existing roof-mounted unit and install, connect and commission its replacement.",workers:"4",supervisor:"",hours:"08:00–17:00",competence:"Site induction, task briefing, working-at-height training and relevant trade competence.",tools:"Hand tools, cordless power tools, lifting accessories and test equipment.",materials:"Replacement plant, fixings, cable, containment and weatherproofing materials.",ppe:"Safety footwear, gloves, hard hat, eye protection and high-visibility clothing.",permits:"Permit to work and roof access authorisation.",isolations:"Electrical and mechanical services to be isolated, locked off and proven dead before work.",emergency:"Stop work, make the area safe, contact the site manager and call 999 for a serious incident.",rescue:"Site-specific work-at-height rescue plan to be briefed before roof access.",welfare:"Use the principal contractor’s designated welfare facilities.",sequence:"1. Sign in, complete induction and receive the daily briefing.\n2. Confirm permits, weather conditions, access and exclusion zones.\n3. Isolate, lock off and prove dead all affected services.\n4. Establish safe roof access and edge protection.\n5. Disconnect and remove the existing unit using the approved lifting plan.\n6. Position, secure and connect the replacement unit.\n7. Inspect, test and commission the installation.\n8. Remove waste, tools and exclusion controls; hand the area back."};
const steps=["Project details","People & work","Hazards","Method","Review"];
const hazardList=["Work at height","Manual handling","Electricity","Power tools","Slips & trips","Asbestos","Lifting operations","Hot works","Noise","Dust / silica","Falling objects","Public interface"];

export default function Home(){
 const[view,setView]=useState<"dashboard"|"create"|"document">("dashboard"),[step,setStep]=useState(0),[selected,setSelected]=useState(["Work at height","Manual handling"]),[form,setForm]=useState<Form>(initial),[submitted,setSubmitted]=useState(false),[risks,setRisks]=useState<Record<string,Risk>>({"Work at height":newRisk(),"Manual handling":newRisk()});
 const set=(key:keyof Form,value:string)=>setForm(f=>({...f,[key]:value}));
 const start=()=>{setView("create");setStep(0);setSubmitted(false)};
 return <div className="shell">
  <aside><div className="brand"><span>R</span><b>RAMS<br/><small>MADE EASY</small></b></div><nav><button className={view==="dashboard"?"active":""} onClick={()=>setView("dashboard")}>⌂ <span>Dashboard</span></button><button className={view==="create"?"active":""} onClick={start}>＋ <span>Create RAMS</span></button><button>▤ <span>RAMS library</span></button><button>▦ <span>Projects & sites</span></button><button>♙ <span>People</span></button></nav><div className="asideBottom"><button>⚙ <span>Settings</span></button><div className="user"><i>AM</i><div><strong>Alex Morgan</strong><small>Company admin</small></div></div></div></aside>
  <main><header className="appHeader"><div><p>RAMS MADE EASY</p><h1>{view==="dashboard"?"Good afternoon, Alex":view==="document"?"RAMS document":"Create a new RAMS"}</h1></div><div className="headActions"><button className="icon">?</button><button className="icon">♢<em>3</em></button>{view==="dashboard"&&<button className="primary" onClick={start}>＋ Create RAMS</button>}</div></header>
  {view==="dashboard"?<Dashboard onCreate={start}/>:view==="document"?<RamsDocument form={form} selected={selected} risks={risks} edit={()=>setView("create")}/>:<Creator step={step} setStep={setStep} selected={selected} toggle={v=>{setSelected(s=>s.includes(v)?s.filter(x=>x!==v):[...s,v]);setRisks(r=>r[v]?r:{...r,[v]:newRisk()})}} risks={risks} updateRisk={(h,k,v)=>setRisks(r=>({...r,[h]:{...(r[h]||newRisk()),[k]:v}}))} form={form} set={set} submitted={submitted} submit={()=>{setSubmitted(true);setView("document")}}/>}</main>
 </div>
}

function Dashboard({onCreate}:{onCreate:()=>void}){return <>
 <section className="notice"><div className="shield">✓</div><div><strong>Your safety documents, under control.</strong><p>Draft with guided assistance. Review by a competent person. Issue with a complete audit trail.</p></div><button>View workflow →</button></section>
 <section className="stats"><article><label>ACTIVE RAMS</label><b>12</b><small><i className="green">↑ 3</i> this month</small></article><article><label>AWAITING REVIEW</label><b>3</b><small>Action required</small></article><article><label>EXPIRING SOON</label><b>2</b><small>Within 14 days</small></article><article><label>WORKER SIGN-OFF</label><b>86%</b><small>43 of 50 briefed</small></article></section>
 <div className="grid"><section className="panel recent"><div className="panelHead"><div><h2>Recent RAMS</h2><p>Your latest safety documents</p></div><button>View all →</button></div>{[["Roof plant replacement","Northgate House, Manchester","RME-0042","In review"],["Ground-floor strip out","Albion Court, Leeds","RME-0041","Approved"],["External lighting repairs","Quayside Apartments, Liverpool","RME-0040","Draft"]].map(j=><div className="job" key={j[2]}><div className="doc">▤</div><div className="jobMain"><strong>{j[0]}</strong><small>{j[1]}</small></div><code>{j[2]}</code><span className={"status "+j[3].replace(" ","").toLowerCase()}>{j[3]}</span><button className="dots">•••</button></div>)}</section>
 <section className="panel actions"><div className="panelHead"><div><h2>Needs your attention</h2><p>Outstanding actions</p></div></div><div className="action"><i>!</i><div><strong>3 RAMS awaiting review</strong><small>Oldest submitted 2 days ago</small></div><button>Review</button></div><div className="action amber"><i>◷</i><div><strong>2 RAMS expire soon</strong><small>Review before they lapse</small></div><button>View</button></div><div className="action blue"><i>♙</i><div><strong>7 briefings outstanding</strong><small>Workers not yet acknowledged</small></div><button>Chase</button></div></section></div>
 <section className="start"><div><span>＋</span><div><h2>Start a new risk assessment & method statement</h2><p>Our guided builder takes you from site details to a review-ready RAMS.</p></div></div><button className="primary" onClick={onCreate}>Create RAMS →</button></section>
 </>}

function RamsDocument({form,selected,risks,edit}:{form:Form,selected:string[],risks:Record<string,Risk>,edit:()=>void}){
 return <div className="documentWrap"><div className="documentActions"><button className="secondary" onClick={edit}>← Edit RAMS</button><button className="primary" onClick={()=>window.print()}>↓ Download / Save as PDF</button></div><article className="ramsDocument">
 <div className="docCover"><div className="docLogo">R</div><div><small>RISK ASSESSMENT & METHOD STATEMENT</small><h2>{form.title}</h2><p>{form.site} · {form.address}</p></div><span className="draftStamp">DRAFT<br/><small>REVIEW REQUIRED</small></span></div>
 <div className="docMeta"><div><label>Reference</label><b>RME-DRAFT-001</b></div><div><label>Version</label><b>1.0</b></div><div><label>Planned start</label><b>{form.start||"To be confirmed"}</b></div><div><label>Review date</label><b>{form.review||"Before work starts"}</b></div></div>
 <DocSection title="1. Project and activity"><p><b>Client / principal contractor:</b> {form.client||"Not supplied"}</p><p><b>Scope:</b> {form.activity}</p><p><b>Workforce:</b> {form.workers} workers · <b>Supervisor:</b> {form.supervisor||"To be appointed"} · <b>Hours:</b> {form.hours}</p></DocSection>
 <DocSection title="2. Competence, equipment and PPE"><p><b>Competence:</b> {form.competence}</p><p><b>Plant and tools:</b> {form.tools}</p><p><b>Materials / substances:</b> {form.materials}</p><p><b>Minimum PPE:</b> {form.ppe}</p></DocSection>
 <DocSection title="3. Risk register"><div className="printTable"><table><thead><tr><th>Hazard / harm / persons</th><th>Controls and responsibility</th><th>Initial</th><th>Residual</th></tr></thead><tbody>{selected.map(h=>{const r=risks[h]||newRisk(),a=r.initialL*r.initialS,b=r.residualL*r.residualS;return <tr key={h}><td><b>{h}</b><br/>{r.harm}<br/><small>{r.people}</small></td><td>{r.controls}<br/><small>Owner: {r.owner}</small></td><td><span className={"printScore "+band(a)}>{a} {label(a)}</span><br/><small>L{r.initialL} × S{r.initialS}</small></td><td><span className={"printScore "+band(b)}>{b} {label(b)}</span><br/><small>L{r.residualL} × S{r.residualS}</small></td></tr>})}</tbody></table></div></DocSection>
 <DocSection title="4. Safe sequence of work"><ol className="methodList">{form.sequence.split("\n").filter(Boolean).map((s,i)=><li key={i}>{s.replace(/^\d+\.\s*/,"")}</li>)}</ol></DocSection>
 <DocSection title="5. Controls and arrangements"><p><b>Permits:</b> {form.permits}</p><p><b>Isolations:</b> {form.isolations}</p><p><b>Emergency:</b> {form.emergency}</p><p><b>Rescue:</b> {form.rescue}</p><p><b>Welfare / housekeeping:</b> {form.welfare}</p></DocSection>
 <DocSection title="6. Review, approval and briefing"><div className="approvalGrid"><div><label>Prepared by</label><span>Alex Morgan</span><small>Date: {new Date().toLocaleDateString("en-GB")}</small></div><div><label>Competent-person review</label><span>Pending</span><small>This draft is not authorised for work.</small></div><div><label>Worker briefing</label><span>Pending</span><small>Acknowledgements recorded after approval.</small></div></div></DocSection>
 <footer className="docFooter">RAMS Made Easy · RME-DRAFT-001 · Version 1.0 · Uncontrolled when printed</footer>
 </article></div>
}
function DocSection({title,children}:{title:string,children:React.ReactNode}){return <section className="docSection"><h3>{title}</h3>{children}</section>}

const Field=({label,value,onChange,area=false,hint}:{label:string,value:string,onChange:(v:string)=>void,area?:boolean,hint?:string})=><label>{label}{area?<textarea value={value} onChange={e=>onChange(e.target.value)}/>:<input value={value} onChange={e=>onChange(e.target.value)}/>} {hint&&<small className="hint">{hint}</small>}</label>;

const band=(n:number)=>n>=17?"veryhigh":n>=10?"high":n>=5?"medium":"low";
const label=(n:number)=>n>=17?"Very high":n>=10?"High":n>=5?"Medium":"Low";
function RiskRegister({selected,risks,update}:{selected:string[],risks:Record<string,Risk>,update:(h:string,k:keyof Risk,v:string|number)=>void}){
 const score=(h:string,k:keyof Risk,v:number)=><select value={v} onChange={e=>update(h,k,Number(e.target.value))}>{[1,2,3,4,5].map(n=><option key={n}>{n}</option>)}</select>;
 return <div className="riskRegister"><div className="riskHead"><div><h3>Detailed construction risk register</h3><p>Identify exposure, apply the hierarchy of controls and score risks before and after controls.</p></div><span>5 × 5 MATRIX</span></div><RiskMatrix/>
 {selected.map(h=>{const r=risks[h]||newRisk(),initial=r.initialL*r.initialS,residual=r.residualL*r.residualS;return <article className="riskRow detailed" key={h}><div className="riskTitle"><strong>{h}</strong><span className={"riskBadge "+band(residual)}>{residual} · {label(residual)} residual risk</span></div><div className="riskFields">
 <label className="wide">Hazardous activity / source<textarea value={r.activity} onChange={e=>update(h,"activity",e.target.value)}/></label><label>Who may be harmed?<textarea value={r.people} onChange={e=>update(h,"people",e.target.value)}/></label><label>Potential harm / consequence<textarea value={r.harm} onChange={e=>update(h,"harm",e.target.value)}/></label>
 <label className="wide">Existing controls<textarea value={r.existing} onChange={e=>update(h,"existing",e.target.value)}/></label><label className="wide">Additional controls required<textarea value={r.controls} onChange={e=>update(h,"controls",e.target.value)}/></label>
 <label>Highest control level<select value={r.hierarchy} onChange={e=>update(h,"hierarchy",e.target.value)}>{["Elimination","Substitution","Engineering control","Administrative control","PPE only"].map(x=><option key={x}>{x}</option>)}</select></label><label>Responsible person<input value={r.owner} onChange={e=>update(h,"owner",e.target.value)}/></label><label>Target date<input value={r.target} onChange={e=>update(h,"target",e.target.value)}/></label><label>Status<select value={r.status} onChange={e=>update(h,"status",e.target.value)}><option>Open</option><option>In progress</option><option>Complete</option><option>Escalated</option></select></label>
 <label className="wide">Relevant legislation / guidance<textarea value={r.legal} onChange={e=>update(h,"legal",e.target.value)}/></label><label className="wide">Competent reviewer comments<textarea placeholder="Completed during review" value={r.reviewer} onChange={e=>update(h,"reviewer",e.target.value)}/></label></div>
 <div className="scores"><div><b>Initial risk</b><label>Likelihood{score(h,"initialL",r.initialL)}</label><label>Severity{score(h,"initialS",r.initialS)}</label><strong className={band(initial)}>{initial} · {label(initial)}</strong></div><span>→ controls →</span><div><b>Residual risk</b><label>Likelihood{score(h,"residualL",r.residualL)}</label><label>Severity{score(h,"residualS",r.residualS)}</label><strong className={band(residual)}>{residual} · {label(residual)}</strong></div></div>
 {r.hierarchy==="PPE only"&&<p className="riskAlert">Controls rely only on PPE. Consider elimination, substitution, engineering or administrative controls first.</p>}{residual>=10&&<p className="riskAlert">Residual risk remains high. Reduce it or escalate it for explicit competent-person acceptance.</p>}</article>})}
 <div className="matrixKey"><span className="low">1–4 Low</span><span className="medium">5–9 Medium</span><span className="high">10–16 High</span><span className="veryhigh">17–25 Very high</span></div></div>
}

function RiskMatrix(){return <div className="riskMatrix"><div className="matrixAxis">Severity →</div><table><tbody>{[5,4,3,2,1].map(l=><tr key={l}>{[1,2,3,4,5].map(s=>{const n=l*s;return <td className={band(n)} key={s}>{n}<small>L{l}×S{s}</small></td>})}</tr>)}</tbody></table><p>Likelihood: 1 Rare · 2 Unlikely · 3 Possible · 4 Likely · 5 Almost certain<br/>Severity: 1 Minor · 2 Moderate · 3 Serious · 4 Major · 5 Fatal / catastrophic</p></div>}

function Creator({step,setStep,selected,toggle,risks,updateRisk,form,set,submitted,submit}:{step:number,setStep:(n:number)=>void,selected:string[],toggle:(v:string)=>void,risks:Record<string,Risk>,updateRisk:(h:string,k:keyof Risk,v:string|number)=>void,form:Form,set:(k:keyof Form,v:string)=>void,submitted:boolean,submit:()=>void}){
 const titles=["Tell us about the project","Who is doing what?","Identify the hazards","Describe the safe system of work","Check before competent-person review"];
 const intros=["These details will appear on the issued document.","Record the people, competence, equipment and scope of work.","Select every hazard relevant to the activity. Each will require suitable controls.","Set out the sequence, permits, isolations and emergency arrangements.","The gap check flags missing information. A competent person must still review and approve the RAMS."];
 const gaps=useMemo(()=>[{ok:!!form.title&&!!form.site,text:"Project and site identified"},{ok:!!form.activity&&!!form.workers,text:"Activity and workforce recorded"},{ok:selected.length>0,text:"Relevant hazards selected"},{ok:form.sequence.split("\n").filter(Boolean).length>=4,text:"Method has at least four clear steps"},{ok:!!form.emergency&&!!form.rescue,text:"Emergency and rescue arrangements recorded"},{ok:!!form.isolations,text:"Energy isolation considered"}],[form,selected]);
 const can=step===0?!!form.title&&!!form.site:step===1?!!form.activity&&!!form.workers:step===2?selected.length>0&&selected.every(h=>{const r=risks[h]||newRisk();return !!r.controls&&r.residualL*r.residualS<10}):step===3?!!form.sequence&&!!form.emergency:true;
 return <div className="creator"><div className="steps">{steps.map((s,i)=><div key={s} className={i===step?"now":i<step?"done":""}><i>{i<step?"✓":i+1}</i><span>{s}</span></div>)}</div>
 <section className="formcard"><div className="formtitle"><label>STEP {step+1} OF 5</label><h2>{titles[step]}</h2><p>{intros[step]}</p></div>
 {step===0&&<div className="fields"><Field label="RAMS title *" value={form.title} onChange={v=>set("title",v)}/><div><Field label="Client / principal contractor" value={form.client} onChange={v=>set("client",v)}/><Field label="Project / site *" value={form.site} onChange={v=>set("site",v)}/></div><Field label="Site address" value={form.address} onChange={v=>set("address",v)} area/><div><label>Planned start<input type="date" value={form.start} onChange={e=>set("start",e.target.value)}/></label><label>Review date<input type="date" value={form.review} onChange={e=>set("review",e.target.value)}/></label></div></div>}
 {step===1&&<div className="fields"><Field label="Activity and scope of work *" value={form.activity} onChange={v=>set("activity",v)} area/><div><Field label="Number of workers *" value={form.workers} onChange={v=>set("workers",v)}/><Field label="Site supervisor" value={form.supervisor} onChange={v=>set("supervisor",v)}/></div><Field label="Working hours" value={form.hours} onChange={v=>set("hours",v)}/><Field label="Competence, training and cards required" value={form.competence} onChange={v=>set("competence",v)} area/><Field label="Plant and tools" value={form.tools} onChange={v=>set("tools",v)} area/><Field label="Materials and substances" value={form.materials} onChange={v=>set("materials",v)} area/><Field label="Minimum PPE" value={form.ppe} onChange={v=>set("ppe",v)} area/></div>}
 {step===2&&<><div className="hazards">{hazardList.map(h=><button className={selected.includes(h)?"picked":""} onClick={()=>toggle(h)} key={h}><i>{selected.includes(h)?"✓":"＋"}</i>{h}</button>)}</div><div className="selectedSummary"><strong>{selected.length} hazards selected</strong><span>Complete the linked risk register below. High residual risks cannot be submitted.</span></div><RiskRegister selected={selected} risks={risks} update={updateRisk}/></>}
 {step===3&&<div className="fields"><Field label="Safe sequence of work *" value={form.sequence} onChange={v=>set("sequence",v)} area hint="Use a new numbered line for each step."/><div><Field label="Permits and authorisations" value={form.permits} onChange={v=>set("permits",v)} area/><Field label="Isolations / lock-off" value={form.isolations} onChange={v=>set("isolations",v)} area/></div><Field label="Emergency arrangements *" value={form.emergency} onChange={v=>set("emergency",v)} area/><Field label="Rescue arrangements" value={form.rescue} onChange={v=>set("rescue",v)} area/><Field label="Welfare and housekeeping" value={form.welfare} onChange={v=>set("welfare",v)} area/></div>}
 {step===4&&<div className="review"><div className="aiCheck"><div><span>✦</span><h3>Document gap check</h3></div><small>Assistance only — this is not approval or competent-person sign-off.</small>{gaps.map(g=><p className={g.ok?"pass":"fail"} key={g.text}><i>{g.ok?"✓":"!"}</i>{g.text}</p>)}</div><div className="reviewGrid"><article><label>PROJECT</label><b>{form.title||"Not supplied"}</b><p>{form.site}<br/>{form.address}</p></article><article><label>WORK</label><b>{form.workers||"0"} workers</b><p>{form.activity}</p></article><article><label>HAZARDS</label><b>{selected.length} selected</b><p>{selected.join(", ")}</p></article><article><label>METHOD</label><b>{form.sequence.split("\n").filter(Boolean).length} work steps</b><p>Permits, isolations, emergency and rescue arrangements included.</p></article></div><div className="warning"><strong>Competent-person review required</strong><p>Submitting sends this draft for human review. It does not approve the work or authorise anyone to start.</p></div>{submitted&&<div className="success"><b>✓ Draft submitted for competent-person review</b><span>When live data is connected, the reviewer will be notified and the audit event recorded.</span></div>}</div>}
 <footer><button className="secondary" disabled={step===0} onClick={()=>setStep(Math.max(0,step-1))}>← Back</button><span>Saved locally as draft</span>{step<4?<button className="primary" disabled={!can} onClick={()=>setStep(step+1)}>Continue →</button>:<button className="primary" disabled={submitted||gaps.some(g=>!g.ok)} onClick={submit}>{submitted?"Submitted":"Submit for review"}</button>}</footer></section></div>
}
