"use client";
import { useMemo, useState } from "react";

type Form={title:string;client:string;site:string;address:string;start:string;review:string;activity:string;workers:string;supervisor:string;hours:string;competence:string;tools:string;materials:string;ppe:string;permits:string;isolations:string;emergency:string;rescue:string;welfare:string;sequence:string};
const initial:Form={title:"Roof plant replacement",client:"",site:"Northgate House",address:"24 Deansgate, Manchester, M3 1AZ",start:"",review:"",activity:"Remove the existing roof-mounted unit and install, connect and commission its replacement.",workers:"4",supervisor:"",hours:"08:00–17:00",competence:"Site induction, task briefing, working-at-height training and relevant trade competence.",tools:"Hand tools, cordless power tools, lifting accessories and test equipment.",materials:"Replacement plant, fixings, cable, containment and weatherproofing materials.",ppe:"Safety footwear, gloves, hard hat, eye protection and high-visibility clothing.",permits:"Permit to work and roof access authorisation.",isolations:"Electrical and mechanical services to be isolated, locked off and proven dead before work.",emergency:"Stop work, make the area safe, contact the site manager and call 999 for a serious incident.",rescue:"Site-specific work-at-height rescue plan to be briefed before roof access.",welfare:"Use the principal contractor’s designated welfare facilities.",sequence:"1. Sign in, complete induction and receive the daily briefing.\n2. Confirm permits, weather conditions, access and exclusion zones.\n3. Isolate, lock off and prove dead all affected services.\n4. Establish safe roof access and edge protection.\n5. Disconnect and remove the existing unit using the approved lifting plan.\n6. Position, secure and connect the replacement unit.\n7. Inspect, test and commission the installation.\n8. Remove waste, tools and exclusion controls; hand the area back."};
const steps=["Project details","People & work","Hazards","Method","Review"];
const hazardList=["Work at height","Manual handling","Electricity","Power tools","Slips & trips","Asbestos","Lifting operations","Hot works","Noise","Dust / silica","Falling objects","Public interface"];

export default function Home(){
 const[view,setView]=useState<"dashboard"|"create">("dashboard"),[step,setStep]=useState(0),[selected,setSelected]=useState(["Work at height","Manual handling"]),[form,setForm]=useState<Form>(initial),[submitted,setSubmitted]=useState(false);
 const set=(key:keyof Form,value:string)=>setForm(f=>({...f,[key]:value}));
 const start=()=>{setView("create");setStep(0);setSubmitted(false)};
 return <div className="shell">
  <aside><div className="brand"><span>R</span><b>RAMS<br/><small>MADE EASY</small></b></div><nav><button className={view==="dashboard"?"active":""} onClick={()=>setView("dashboard")}>⌂ <span>Dashboard</span></button><button className={view==="create"?"active":""} onClick={start}>＋ <span>Create RAMS</span></button><button>▤ <span>RAMS library</span></button><button>▦ <span>Projects & sites</span></button><button>♙ <span>People</span></button></nav><div className="asideBottom"><button>⚙ <span>Settings</span></button><div className="user"><i>AM</i><div><strong>Alex Morgan</strong><small>Company admin</small></div></div></div></aside>
  <main><header><div><p>RAMS MADE EASY</p><h1>{view==="dashboard"?"Good afternoon, Alex":"Create a new RAMS"}</h1></div><div className="headActions"><button className="icon">?</button><button className="icon">♢<em>3</em></button>{view==="dashboard"&&<button className="primary" onClick={start}>＋ Create RAMS</button>}</div></header>
  {view==="dashboard"?<Dashboard onCreate={start}/>:<Creator step={step} setStep={setStep} selected={selected} toggle={v=>setSelected(s=>s.includes(v)?s.filter(x=>x!==v):[...s,v])} form={form} set={set} submitted={submitted} submit={()=>setSubmitted(true)}/>}</main>
 </div>
}

function Dashboard({onCreate}:{onCreate:()=>void}){return <>
 <section className="notice"><div className="shield">✓</div><div><strong>Your safety documents, under control.</strong><p>Draft with guided assistance. Review by a competent person. Issue with a complete audit trail.</p></div><button>View workflow →</button></section>
 <section className="stats"><article><label>ACTIVE RAMS</label><b>12</b><small><i className="green">↑ 3</i> this month</small></article><article><label>AWAITING REVIEW</label><b>3</b><small>Action required</small></article><article><label>EXPIRING SOON</label><b>2</b><small>Within 14 days</small></article><article><label>WORKER SIGN-OFF</label><b>86%</b><small>43 of 50 briefed</small></article></section>
 <div className="grid"><section className="panel recent"><div className="panelHead"><div><h2>Recent RAMS</h2><p>Your latest safety documents</p></div><button>View all →</button></div>{[["Roof plant replacement","Northgate House, Manchester","RME-0042","In review"],["Ground-floor strip out","Albion Court, Leeds","RME-0041","Approved"],["External lighting repairs","Quayside Apartments, Liverpool","RME-0040","Draft"]].map(j=><div className="job" key={j[2]}><div className="doc">▤</div><div className="jobMain"><strong>{j[0]}</strong><small>{j[1]}</small></div><code>{j[2]}</code><span className={"status "+j[3].replace(" ","").toLowerCase()}>{j[3]}</span><button className="dots">•••</button></div>)}</section>
 <section className="panel actions"><div className="panelHead"><div><h2>Needs your attention</h2><p>Outstanding actions</p></div></div><div className="action"><i>!</i><div><strong>3 RAMS awaiting review</strong><small>Oldest submitted 2 days ago</small></div><button>Review</button></div><div className="action amber"><i>◷</i><div><strong>2 RAMS expire soon</strong><small>Review before they lapse</small></div><button>View</button></div><div className="action blue"><i>♙</i><div><strong>7 briefings outstanding</strong><small>Workers not yet acknowledged</small></div><button>Chase</button></div></section></div>
 <section className="start"><div><span>＋</span><div><h2>Start a new risk assessment & method statement</h2><p>Our guided builder takes you from site details to a review-ready RAMS.</p></div></div><button className="primary" onClick={onCreate}>Create RAMS →</button></section>
 </>}

const Field=({label,value,onChange,area=false,hint}:{label:string,value:string,onChange:(v:string)=>void,area?:boolean,hint?:string})=><label>{label}{area?<textarea value={value} onChange={e=>onChange(e.target.value)}/>:<input value={value} onChange={e=>onChange(e.target.value)}/>} {hint&&<small className="hint">{hint}</small>}</label>;

function Creator({step,setStep,selected,toggle,form,set,submitted,submit}:{step:number,setStep:(n:number)=>void,selected:string[],toggle:(v:string)=>void,form:Form,set:(k:keyof Form,v:string)=>void,submitted:boolean,submit:()=>void}){
 const titles=["Tell us about the project","Who is doing what?","Identify the hazards","Describe the safe system of work","Check before competent-person review"];
 const intros=["These details will appear on the issued document.","Record the people, competence, equipment and scope of work.","Select every hazard relevant to the activity. Each will require suitable controls.","Set out the sequence, permits, isolations and emergency arrangements.","The gap check flags missing information. A competent person must still review and approve the RAMS."];
 const gaps=useMemo(()=>[{ok:!!form.title&&!!form.site,text:"Project and site identified"},{ok:!!form.activity&&!!form.workers,text:"Activity and workforce recorded"},{ok:selected.length>0,text:"Relevant hazards selected"},{ok:form.sequence.split("\n").filter(Boolean).length>=4,text:"Method has at least four clear steps"},{ok:!!form.emergency&&!!form.rescue,text:"Emergency and rescue arrangements recorded"},{ok:!!form.isolations,text:"Energy isolation considered"}],[form,selected]);
 const can=step===0?!!form.title&&!!form.site:step===1?!!form.activity&&!!form.workers:step===2?selected.length>0:step===3?!!form.sequence&&!!form.emergency:true;
 return <div className="creator"><div className="steps">{steps.map((s,i)=><div key={s} className={i===step?"now":i<step?"done":""}><i>{i<step?"✓":i+1}</i><span>{s}</span></div>)}</div>
 <section className="formcard"><div className="formtitle"><label>STEP {step+1} OF 5</label><h2>{titles[step]}</h2><p>{intros[step]}</p></div>
 {step===0&&<div className="fields"><Field label="RAMS title *" value={form.title} onChange={v=>set("title",v)}/><div><Field label="Client / principal contractor" value={form.client} onChange={v=>set("client",v)}/><Field label="Project / site *" value={form.site} onChange={v=>set("site",v)}/></div><Field label="Site address" value={form.address} onChange={v=>set("address",v)} area/><div><label>Planned start<input type="date" value={form.start} onChange={e=>set("start",e.target.value)}/></label><label>Review date<input type="date" value={form.review} onChange={e=>set("review",e.target.value)}/></label></div></div>}
 {step===1&&<div className="fields"><Field label="Activity and scope of work *" value={form.activity} onChange={v=>set("activity",v)} area/><div><Field label="Number of workers *" value={form.workers} onChange={v=>set("workers",v)}/><Field label="Site supervisor" value={form.supervisor} onChange={v=>set("supervisor",v)}/></div><Field label="Working hours" value={form.hours} onChange={v=>set("hours",v)}/><Field label="Competence, training and cards required" value={form.competence} onChange={v=>set("competence",v)} area/><Field label="Plant and tools" value={form.tools} onChange={v=>set("tools",v)} area/><Field label="Materials and substances" value={form.materials} onChange={v=>set("materials",v)} area/><Field label="Minimum PPE" value={form.ppe} onChange={v=>set("ppe",v)} area/></div>}
 {step===2&&<><div className="hazards">{hazardList.map(h=><button className={selected.includes(h)?"picked":""} onClick={()=>toggle(h)} key={h}><i>{selected.includes(h)?"✓":"＋"}</i>{h}</button>)}</div><div className="selectedSummary"><strong>{selected.length} hazards selected</strong><span>Risk scores and task-specific controls will be completed during the controlled assessment stage.</span></div></>}
 {step===3&&<div className="fields"><Field label="Safe sequence of work *" value={form.sequence} onChange={v=>set("sequence",v)} area hint="Use a new numbered line for each step."/><div><Field label="Permits and authorisations" value={form.permits} onChange={v=>set("permits",v)} area/><Field label="Isolations / lock-off" value={form.isolations} onChange={v=>set("isolations",v)} area/></div><Field label="Emergency arrangements *" value={form.emergency} onChange={v=>set("emergency",v)} area/><Field label="Rescue arrangements" value={form.rescue} onChange={v=>set("rescue",v)} area/><Field label="Welfare and housekeeping" value={form.welfare} onChange={v=>set("welfare",v)} area/></div>}
 {step===4&&<div className="review"><div className="aiCheck"><div><span>✦</span><h3>Document gap check</h3></div><small>Assistance only — this is not approval or competent-person sign-off.</small>{gaps.map(g=><p className={g.ok?"pass":"fail"} key={g.text}><i>{g.ok?"✓":"!"}</i>{g.text}</p>)}</div><div className="reviewGrid"><article><label>PROJECT</label><b>{form.title||"Not supplied"}</b><p>{form.site}<br/>{form.address}</p></article><article><label>WORK</label><b>{form.workers||"0"} workers</b><p>{form.activity}</p></article><article><label>HAZARDS</label><b>{selected.length} selected</b><p>{selected.join(", ")}</p></article><article><label>METHOD</label><b>{form.sequence.split("\n").filter(Boolean).length} work steps</b><p>Permits, isolations, emergency and rescue arrangements included.</p></article></div><div className="warning"><strong>Competent-person review required</strong><p>Submitting sends this draft for human review. It does not approve the work or authorise anyone to start.</p></div>{submitted&&<div className="success"><b>✓ Draft submitted for competent-person review</b><span>When live data is connected, the reviewer will be notified and the audit event recorded.</span></div>}</div>}
 <footer><button className="secondary" disabled={step===0} onClick={()=>setStep(Math.max(0,step-1))}>← Back</button><span>Saved locally as draft</span>{step<4?<button className="primary" disabled={!can} onClick={()=>setStep(step+1)}>Continue →</button>:<button className="primary" disabled={submitted||gaps.some(g=>!g.ok)} onClick={submit}>{submitted?"Submitted":"Submit for review"}</button>}</footer></section></div>
}
